### ISSUE TITLE
after submission is done create a readme file for the project 

### ISSUE THREAD

**Issue by him1411** [him1411/ps1-project-eee-bsp#5]
@Salil-Jain @Mihir1996  @Anshul2166-sophos

**Comment by him1411** [comment]
readme file updated. @Salil-Jain @anshul2166-sophos @Mihir1996, review and give suggestions

**Comment by Salil-Jain** [comment]
Updated my I.D. as it was wrong and added the link to Final Report. Everything else looks fine. :+1:

**Comment by him1411** [comment]
@Salil-Jain thanks
